version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
